export const appUrl = {
  homePage: "/home",
  searchPage: "/search",
  loginPage: "/login",
  profile: "/admin/profile",
  forgotPasswordPage: "/forgot-password",
  signupPage: "/signup",
  productDetailPage: "/product-detail",
  createUserPage: "/create-user",
  userPage: "/profile",
  userManagementPage: "/user-management",
  productManagementPage: "/product-management",
  createProductPage: "/create-product",
  campaignManagementPage: "/campaign-management",
  campaignDetailPage: "/view-campaign",
  createCampaignPage: "/create-campaign",

  adminDefaultPage: "/admin/user-management",
  importerDefaultPage: "/admin/profile",
  RetailerDefaultPage: "/admin/profile",
  updateItemPage: "/admin/create-item-page",
};
